name: Run index.js daily at 23:55 UTC

on:
  schedule:
    - cron: '55 23 * * *'  # 23:55 UTC todos os dias
  workflow_dispatch:  # Permite disparar manualmente via interface do GitHub

jobs:
  run-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install discord.js moment dotenv  # Instala as dependências necessárias

      - name: Run index.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          BIRTHDAY_CHANNEL_ID: ${{ secrets.BIRTHDAY_CHANNEL_ID }}
          GENERAL_CHANNEL_ID: ${{ secrets.GENERAL_CHANNEL_ID }}
        run: node index.js  # Executa o arquivo index.js
